### PR TITLE
milestone 1 finished

### PR DESCRIPTION
**Pull request by andypasso**
created app with create-react-app
adde big.js
readme will be updated at the end of the last milestone.

### CODE REVIEW

**Comment by andypasso** [comment]
failed checks are because on Microverse lints page , we are told to use older packages versions. 
you can find details on this [here](https://github.com/microverseinc/linters-config/tree/master/react-redux)

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Required❌ 
# 🙋‍♂️ @andynarf,
#### You have done a great job so far, but there are issues we have to address🤗.
* [ ]  In relation to the comment on the pull request. There is always something to clarify especially when the focus of the review is not to focus on having a detailed Readme at this stage. Kindly describe what you did in this milestone irrespective of how small it is.
* [ ] Kindly make sure the linter checks are all passing. Linters should always be green on every code review you submit. this is a mandatory requirement.

**[OPTIONAL]**

- Kindly make it a habit to always add a description to every repository you create on Github.

### That is it, kindly make the changes and submit a re-review😎.
#### Happy coding👨‍💻 
Addo Forison

**Comment by andypasso** [comment]
please read the comment I made about lints @Forison

**Review by mosaaleb — CHANGES_REQUESTED** [review]
#### Well done @andynarf :clap:

I see that you have handled the requirements from the previous review, yet there is only one requirement to handle before moving on:

- [x] Please deploy the app to Heroku and make sure the Heroku app works correctly.
- [x] Add the live link to read-me file with little summary about the app. You can still work on the read-me while your progressing through the remaining milestones.



Good luck with the next submission.

##### Muhammad Ebeid

**Review by bellom — APPROVED** [review]
Hi @andynarf 

**Kindly update your `README` file before merging, I trust you can do this, 👀  on it**.
Checkout out the below link for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

**Note:** Your PR would be marked as invalid if you're not following the 3 basic rules in Microverse projects
image


### Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
